Update bzyq

diff --git a/bzyq b/bzyq
--- a/bzyq
+++ b/bzyq
@@ -9,12 +9,14 @@ cd /tmp
 
 wget -q https://enigma2.hswg.pl/wp-content/uploads/2024/04/Lista-bzyk83-hb-13E-15.04.2024.zip
 if [ $? -gt 0 ] ;then
-[ $isPL -eq 1 ] && echo "błąd pobierania archiwum, koniec" || echo "error downloading archive, end"
-exit 1
+   [ $isPL -eq 1 ] && echo "błąd pobierania archiwum, koniec" || echo "error downloading archive, end"
+   exit 1
 fi
+
 else
 	[ $isPL -eq 1 ] && echo "Archiwum pobrane" || echo "Archive downloaded"
 fi
+
 unzip /tmp/Lista-bzyk83*.zip -d /tmp >/dev/null 2>&1
 if [ $? -gt 0 ] ;then
 	[ $isPL -eq 1 ] && echo "błąd rozpakowania archiwum, koniec" || echo "error extracting archive, end"
