Update bzyq

diff --git a/bzyq b/bzyq
--- a/bzyq
+++ b/bzyq
@@ -7,23 +7,21 @@ init 4
 
 cd /tmp
 
-wget -q https://enigma2.hswg.pl/wp-content/uploads/2024/04/Lista-bzyk83-hb-13E-15.04.2024.zip
+wget -q "--no-check-certificate" https://enigma2.hswg.pl/wp-content/uploads/2024/04/Lista-bzyk83-hb-13E-15.04.2024.zip
 if [ $? -gt 0 ] ;then
-  wget -q "--no-check-certificate" https://enigma2.hswg.pl/wp-content/uploads/2024/04/Lista-bzyk83-hb-13E-15.04.2024.zip
-  if [ $? -gt 0 ] ;then
-    [ $isPL -eq 1 ] && echo "błąd pobierania archiwum, koniec" || echo "error downloading archive, end"
-    exit 1
-  fi
+[ $isPL -eq 1 ] && echo "błąd pobierania archiwum, koniec" || echo "error downloading archive, end"
+exit 1
+fi
 else
 	[ $isPL -eq 1 ] && echo "Archiwum pobrane" || echo "Archive downloaded"
 fi
-unzip /tmp/Lista-bzyk83-hb-13E-15.04.2024.zip -d /tmp
+unzip /tmp/Lista-bzyk83*.zip -d /tmp
 if [ $? -gt 0 ] ;then
 	[ $isPL -eq 1 ] && echo "błąd rozpakowania archiwum, koniec" || echo "error extracting archive, end"
 	exit 1
 else
 	[ $isPL -eq 1 ] && echo "Archiwum rozpakowane" || echo "Archive extracted"
-	rm -f /tmp/Lista-bzyk83-hb-13E-15.04.2024.zip 
+	rm -f /tmp/Lista-bzyk83*.zip 
 fi
 
 pyVer=`python -c "import sys;print(sys.version_info.major)"`
@@ -40,18 +38,18 @@ rm -f /etc/enigma2/*.tv
 rm -f /etc/enigma2/*.radio
 rm -f /etc/tuxbox/satellites.xml
 
-cp -f /tmp/Lista*bzyk83*hb*13E*15.04.2024/lamedb /etc/enigma2/
-cp -f /tmp/Lista*bzyk83*hb*13E*15.04.2024/blacklist /etc/enigma2/
-cp -f /tmp/Lista*bzyk83*hb*13E*15.04.2024/*.tv /etc/enigma2/
-cp -f /tmp/Lista*bzyk83*hb*13E*15.04.2024/*.radio /etc/enigma2/
-cp -f /tmp/Lista*bzyk83*hb*13E*15.04.2024/satellites.xml /etc/tuxbox/
+cp -f /tmp/Lista*bzyk83*/lamedb /etc/enigma2/
+cp -f /tmp/Lista*bzyk83*/blacklist /etc/enigma2/
+cp -f /tmp/Lista*bzyk83*/*.tv /etc/enigma2/
+cp -f /tmp/Lista*bzyk83*/*.radio /etc/enigma2/
+cp -f /tmp/Lista*bzyk83*/satellites.xml /etc/tuxbox/
 
 if [ $? -gt 0 ] ;then
 	[ $isPL -eq 1 ] && echo "błąd instalacji listy, koniec" || echo "error installing list, end"
 	exit 1
 else
 	[ $isPL -eq 1 ] && echo "Lista zainstalowana" || echo "Channellist installed"
-	rm -rf /tmp/Lista*bzyk83*hb*13E*15.04.2024 >/dev/null 2>&1
+	rm -rf /tmp/Lista*bzyk83* >/dev/null 2>&1
 fi
 
 [ $isPL -eq 1 ] && echo "KONIEC. restartuje E2..." || echo "END. restarting E2..."
