Update bzyq

diff --git a/bzyq b/bzyq
--- a/bzyq
+++ b/bzyq
@@ -1,43 +1,44 @@
 
 #!/bin/bash
 
+[ `grep -c 'osd.language=pl_PL' </etc/enigma2/settings` -gt 0 ] && isPL=1 || isPL=0
+
 init 4
 
 cd /tmp
-
-[ -e /tmp/Lista-bzyk83-hb-13E-15.04.2024.zip ] && rm -f /tmp/Lista-bzyk83-hb-13E-15.04.2024.zip
-[ -e /tmp/Lista bzyk83 hb 13E 15.04.2024 ] && rm -fr /tmp/Lista bzyk83 hb 13E 15.04.2024
 
 wget -q https://enigma2.hswg.pl/wp-content/uploads/2024/04/Lista-bzyk83-hb-13E-15.04.2024.zip
 if [ $? -gt 0 ] ;then
   wget -q "--no-check-certificate" https://enigma2.hswg.pl/wp-content/uploads/2024/04/Lista-bzyk83-hb-13E-15.04.2024.zip
   if [ $? -gt 0 ] ;then
-  
- echo "błąd pobierania archiwum, koniec"
- 
+    [ $isPL -eq 1 ] && echo "błąd pobierania archiwum, koniec" || echo "error downloading archive, end"
     exit 1
   fi
 else
-
-echo "Archiwum pobrane"
-
+	[ $isPL -eq 1 ] && echo "Archiwum pobrane" || echo "Archive downloaded"
 fi
-unzip /tmp/Lista-bzyk83-hb-13E-15.04.2024.zip -d /tmp >/dev/null 2>&1
+unzip /tmp/channellist-main.zip >/dev/null 2>&1
 if [ $? -gt 0 ] ;then
-
-echo "błąd rozpakowania archiwum, koniec"
-
+	[ $isPL -eq 1 ] && echo "błąd rozpakowania archiwum, koniec" || echo "error extracting archive, end"
 	exit 1
-  fi
 else
+	[ $isPL -eq 1 ] && echo "Archiwum rozpakowane" || echo "Archive extracted"
+	rm -f /tmp/Lista-bzyk83-hb-13E-15.04.2024.zip 
+fi
 
-echo "Archiwum rozpakowane"
+pyVer=`python -c "import sys;print(sys.version_info.major)"`
 
-	rm -rf /etc/enigma2/lamedb >/dev/null 2>&1
-	rm -rf /etc/enigma2/blacklist >/dev/null 2>&1
-        rm -f /etc/enigma2/*.tv
-        rm -f /etc/enigma2/*.radio
-	rm -f /etc/tuxbox/satellites.xml
+if [ $pyVer -eq 2 ];then
+	[ $isPL -eq 1 ] && echo "Wykryto system z python2" || echo "Found system using python2"
+else
+	[ $isPL -eq 1 ] && echo "Wykryto system z python3" || echo "Found system using python3"
+fi
+
+rm -rf /etc/enigma2/lamedb >/dev/null 2>&1
+rm -rf /etc/enigma2/blacklist >/dev/null 2>&1
+rm -f /etc/enigma2/*.tv
+rm -f /etc/enigma2/*.radio
+rm -f /etc/tuxbox/satellites.xml
 
 mv -f /tmp/Lista bzyk83 hb 13E 15.04.2024/lamedb /etc/enigma2/
 mv -f /tmp/Lista bzyk83 hb 13E 15.04.2024/blacklist /etc/enigma2/
@@ -45,24 +46,14 @@ mv -f /tmp/Lista bzyk83 hb 13E 15.04.2024/*.tv /etc/enigma2/
 mv -f /tmp/Lista bzyk83 hb 13E 15.04.2024/list/*.radio /etc/enigma2/
 mv -f /tmp/Lista bzyk83 hb 13E 15.04.2024/list/satellites.xml /etc/tuxbox/
 
-
-
 if [ $? -gt 0 ] ;then
-
-echo "błąd instalacji listy, koniec"
-
+	[ $isPL -eq 1 ] && echo "błąd instalacji listy, koniec" || echo "error installing list, end"
 	exit 1
-  fi
 else
-
-echo "Lista zainstalowana"
-
-	rm -f /tmp/Lista-bzyk83-hb-13E-15.04.2024.zip >/dev/null 2>&1
+	[ $isPL -eq 1 ] && echo "Lista zainstalowana" || echo "Channellist installed"
 	rm -rf /tmp/Lista bzyk83 hb 13E 15.04.2024 >/dev/null 2>&1
+fi
 
-
-echo "KONIEC. restartuje E2..."
+[ $isPL -eq 1 ] && echo "KONIEC. restartuje E2..." || echo "END. restarting E2..."
 
 init 3
-sleep 5
-exit 0
